apiVersion: v1
kind: Service
metadata:
  name: user-input
  labels:
    name: user-input-service
    app: user-login-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: user-input-pod
    app: user-login-app