apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: user-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysqldb-pod
      app: user-login-app
  template:
    metadata:
      name: mysqldb
      labels:
        name: mysqldb-pod
        app: user-login-app
    spec:
      containers:
      - name: mysql
        image: adarsha/kub_demo_mysqldb:3.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: persistent-volume
          mountPath: /var/lib/mysql
      nodeSelector:
        type: backend
      volumes:
      - name: persistent-volume
        hostPath:
          path: /var/mysql_kub_backup
          type: DirectoryOrCreate
