apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysqldb-service
    app: user-login-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysqldb-pod
    app: user-login-app