apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: application-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application-deploy
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
